/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SecretaireRouteImport } from './routes/secretaire'
import { Route as PharmacienRouteImport } from './routes/pharmacien'
import { Route as PatientRouteImport } from './routes/patient'
import { Route as MedecinRouteImport } from './routes/medecin'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InfirmierRouteImport } from './routes/infirmier'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ForbiddenRouteImport } from './routes/forbidden'
import { Route as DirecteurRouteImport } from './routes/directeur'
import { Route as ComptableRouteImport } from './routes/comptable'
import { Route as CentreRouteImport } from './routes/centre'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminUtilisateursRouteImport } from './routes/admin/utilisateurs'
import { Route as AdminRendezVousRouteImport } from './routes/admin/rendez-vous'
import { Route as AdminPharmacieRouteImport } from './routes/admin/pharmacie'
import { Route as AdminPatientsRouteImport } from './routes/admin/patients'

const SecretaireRoute = SecretaireRouteImport.update({
  id: '/secretaire',
  path: '/secretaire',
  getParentRoute: () => rootRouteImport,
} as any)
const PharmacienRoute = PharmacienRouteImport.update({
  id: '/pharmacien',
  path: '/pharmacien',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientRoute = PatientRouteImport.update({
  id: '/patient',
  path: '/patient',
  getParentRoute: () => rootRouteImport,
} as any)
const MedecinRoute = MedecinRouteImport.update({
  id: '/medecin',
  path: '/medecin',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InfirmierRoute = InfirmierRouteImport.update({
  id: '/infirmier',
  path: '/infirmier',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ForbiddenRoute = ForbiddenRouteImport.update({
  id: '/forbidden',
  path: '/forbidden',
  getParentRoute: () => rootRouteImport,
} as any)
const DirecteurRoute = DirecteurRouteImport.update({
  id: '/directeur',
  path: '/directeur',
  getParentRoute: () => rootRouteImport,
} as any)
const ComptableRoute = ComptableRouteImport.update({
  id: '/comptable',
  path: '/comptable',
  getParentRoute: () => rootRouteImport,
} as any)
const CentreRoute = CentreRouteImport.update({
  id: '/centre',
  path: '/centre',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUtilisateursRoute = AdminUtilisateursRouteImport.update({
  id: '/admin/utilisateurs',
  path: '/admin/utilisateurs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRendezVousRoute = AdminRendezVousRouteImport.update({
  id: '/admin/rendez-vous',
  path: '/admin/rendez-vous',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPharmacieRoute = AdminPharmacieRouteImport.update({
  id: '/admin/pharmacie',
  path: '/admin/pharmacie',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPatientsRoute = AdminPatientsRouteImport.update({
  id: '/admin/patients',
  path: '/admin/patients',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/centre': typeof CentreRoute
  '/comptable': typeof ComptableRoute
  '/directeur': typeof DirecteurRoute
  '/forbidden': typeof ForbiddenRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/infirmier': typeof InfirmierRoute
  '/login': typeof LoginRoute
  '/medecin': typeof MedecinRoute
  '/patient': typeof PatientRoute
  '/pharmacien': typeof PharmacienRoute
  '/secretaire': typeof SecretaireRoute
  '/admin/patients': typeof AdminPatientsRoute
  '/admin/pharmacie': typeof AdminPharmacieRoute
  '/admin/rendez-vous': typeof AdminRendezVousRoute
  '/admin/utilisateurs': typeof AdminUtilisateursRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/centre': typeof CentreRoute
  '/comptable': typeof ComptableRoute
  '/directeur': typeof DirecteurRoute
  '/forbidden': typeof ForbiddenRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/infirmier': typeof InfirmierRoute
  '/login': typeof LoginRoute
  '/medecin': typeof MedecinRoute
  '/patient': typeof PatientRoute
  '/pharmacien': typeof PharmacienRoute
  '/secretaire': typeof SecretaireRoute
  '/admin/patients': typeof AdminPatientsRoute
  '/admin/pharmacie': typeof AdminPharmacieRoute
  '/admin/rendez-vous': typeof AdminRendezVousRoute
  '/admin/utilisateurs': typeof AdminUtilisateursRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/centre': typeof CentreRoute
  '/comptable': typeof ComptableRoute
  '/directeur': typeof DirecteurRoute
  '/forbidden': typeof ForbiddenRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/infirmier': typeof InfirmierRoute
  '/login': typeof LoginRoute
  '/medecin': typeof MedecinRoute
  '/patient': typeof PatientRoute
  '/pharmacien': typeof PharmacienRoute
  '/secretaire': typeof SecretaireRoute
  '/admin/patients': typeof AdminPatientsRoute
  '/admin/pharmacie': typeof AdminPharmacieRoute
  '/admin/rendez-vous': typeof AdminRendezVousRoute
  '/admin/utilisateurs': typeof AdminUtilisateursRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/centre'
    | '/comptable'
    | '/directeur'
    | '/forbidden'
    | '/forgot-password'
    | '/infirmier'
    | '/login'
    | '/medecin'
    | '/patient'
    | '/pharmacien'
    | '/secretaire'
    | '/admin/patients'
    | '/admin/pharmacie'
    | '/admin/rendez-vous'
    | '/admin/utilisateurs'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/centre'
    | '/comptable'
    | '/directeur'
    | '/forbidden'
    | '/forgot-password'
    | '/infirmier'
    | '/login'
    | '/medecin'
    | '/patient'
    | '/pharmacien'
    | '/secretaire'
    | '/admin/patients'
    | '/admin/pharmacie'
    | '/admin/rendez-vous'
    | '/admin/utilisateurs'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/centre'
    | '/comptable'
    | '/directeur'
    | '/forbidden'
    | '/forgot-password'
    | '/infirmier'
    | '/login'
    | '/medecin'
    | '/patient'
    | '/pharmacien'
    | '/secretaire'
    | '/admin/patients'
    | '/admin/pharmacie'
    | '/admin/rendez-vous'
    | '/admin/utilisateurs'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CentreRoute: typeof CentreRoute
  ComptableRoute: typeof ComptableRoute
  DirecteurRoute: typeof DirecteurRoute
  ForbiddenRoute: typeof ForbiddenRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  InfirmierRoute: typeof InfirmierRoute
  LoginRoute: typeof LoginRoute
  MedecinRoute: typeof MedecinRoute
  PatientRoute: typeof PatientRoute
  PharmacienRoute: typeof PharmacienRoute
  SecretaireRoute: typeof SecretaireRoute
  AdminPatientsRoute: typeof AdminPatientsRoute
  AdminPharmacieRoute: typeof AdminPharmacieRoute
  AdminRendezVousRoute: typeof AdminRendezVousRoute
  AdminUtilisateursRoute: typeof AdminUtilisateursRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/secretaire': {
      id: '/secretaire'
      path: '/secretaire'
      fullPath: '/secretaire'
      preLoaderRoute: typeof SecretaireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pharmacien': {
      id: '/pharmacien'
      path: '/pharmacien'
      fullPath: '/pharmacien'
      preLoaderRoute: typeof PharmacienRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient': {
      id: '/patient'
      path: '/patient'
      fullPath: '/patient'
      preLoaderRoute: typeof PatientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medecin': {
      id: '/medecin'
      path: '/medecin'
      fullPath: '/medecin'
      preLoaderRoute: typeof MedecinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/infirmier': {
      id: '/infirmier'
      path: '/infirmier'
      fullPath: '/infirmier'
      preLoaderRoute: typeof InfirmierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forbidden': {
      id: '/forbidden'
      path: '/forbidden'
      fullPath: '/forbidden'
      preLoaderRoute: typeof ForbiddenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/directeur': {
      id: '/directeur'
      path: '/directeur'
      fullPath: '/directeur'
      preLoaderRoute: typeof DirecteurRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comptable': {
      id: '/comptable'
      path: '/comptable'
      fullPath: '/comptable'
      preLoaderRoute: typeof ComptableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/centre': {
      id: '/centre'
      path: '/centre'
      fullPath: '/centre'
      preLoaderRoute: typeof CentreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/utilisateurs': {
      id: '/admin/utilisateurs'
      path: '/admin/utilisateurs'
      fullPath: '/admin/utilisateurs'
      preLoaderRoute: typeof AdminUtilisateursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/rendez-vous': {
      id: '/admin/rendez-vous'
      path: '/admin/rendez-vous'
      fullPath: '/admin/rendez-vous'
      preLoaderRoute: typeof AdminRendezVousRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/pharmacie': {
      id: '/admin/pharmacie'
      path: '/admin/pharmacie'
      fullPath: '/admin/pharmacie'
      preLoaderRoute: typeof AdminPharmacieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/patients': {
      id: '/admin/patients'
      path: '/admin/patients'
      fullPath: '/admin/patients'
      preLoaderRoute: typeof AdminPatientsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CentreRoute: CentreRoute,
  ComptableRoute: ComptableRoute,
  DirecteurRoute: DirecteurRoute,
  ForbiddenRoute: ForbiddenRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  InfirmierRoute: InfirmierRoute,
  LoginRoute: LoginRoute,
  MedecinRoute: MedecinRoute,
  PatientRoute: PatientRoute,
  PharmacienRoute: PharmacienRoute,
  SecretaireRoute: SecretaireRoute,
  AdminPatientsRoute: AdminPatientsRoute,
  AdminPharmacieRoute: AdminPharmacieRoute,
  AdminRendezVousRoute: AdminRendezVousRoute,
  AdminUtilisateursRoute: AdminUtilisateursRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
